import '../../globals.css';
import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import { storyblokInit, apiPlugin } from '@storyblok/react';

import Page from '@/components/Page';
import Hero from '@/components/Hero';
import CompaniesBanner from '@/components/CompaniesBanner';
import About from '@/components/About';
import Services from '@/components/Services';
import CostumersSaying from '@/components/CostumersSaying';
import RecentProjectsSection from '@/components/RecentProjectsSection';
import CtaSection from '@/components/CtaSection';
import Contact from '@/components/Contact';
import CarRentalSection from '@/components/CarRentalSection';
import StoryblokBridgeLoader from '@storyblok/react/bridge-loader';

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  components: {
    page: Page,
    hero: Hero,
    companiesBanner: CompaniesBanner,
    services: Services,
    about: About,
    whatCostumersAreSaying: CostumersSaying,
    recentProjectSection: RecentProjectsSection,
    ctaSection: CtaSection,
    contact: Contact,
    carRental: CarRentalSection,
  },
});

const lexend = Lexend({
  subsets: ['latin'],
  variable: '--font-lexend',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='scroll-smooth'>
      <body className={`${lexend.variable} font-sans`}>{children}</body>
      <StoryblokBridgeLoader options={{}} />
    </html>
  );
}
