import './globals.css';
import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import { storyblokInit, apiPlugin } from '@storyblok/react/rsc';

import StoryblokProvider from '@/components/StoryblokProvider';
import Page from '@/components/Page';
import Grid from '@/components/Grid';
import Feature from '@/components/Feature';
import Teaser from '@/components/Teaser';
import Hero from '@/components/Hero';
import CompaniesBanner from '@/components/CompaniesBanner';
import About from '@/components/About';
import Services from '@/components/Services';
import CostumersSaying from '@/components/CostumersSaying';

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
  components: {
    page: Page,
    grid: Grid,
    feature: Feature,
    teaser: Teaser,
    hero: Hero,
    companiesBanner: CompaniesBanner,
    services: Services,
    about: About,
    whatCostumersAreSaying: CostumersSaying,
  },
});

const lexend = Lexend({
  subsets: ['latin'],
  variable: '--font-lexend',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoryblokProvider>
      <html lang='en'>
        <body className={`${lexend.variable} font-sans`}>{children}</body>
      </html>
    </StoryblokProvider>
  );
}
